# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 617)
        MainWindow.setBaseSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tasksListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.tasksListWidget.setGeometry(QtCore.QRect(0, 0, 201, 571))
        self.tasksListWidget.setObjectName("tasksListWidget")
        self.description = QtWidgets.QTextBrowser(self.centralwidget)
        self.description.setGeometry(QtCore.QRect(210, 100, 611, 321))
        self.description.setObjectName("description")
        self.profileInfo = QtWidgets.QLabel(self.centralwidget)
        self.profileInfo.setGeometry(QtCore.QRect(210, 10, 291, 81))
        self.profileInfo.setObjectName("profileInfo")
        self.additInterface = QtWidgets.QGroupBox(self.centralwidget)
        self.additInterface.setGeometry(QtCore.QRect(209, 429, 611, 141))
        self.additInterface.setTitle("")
        self.additInterface.setObjectName("additInterface")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.additInterface)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 611, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tasksInfo = QtWidgets.QLabel(self.centralwidget)
        self.tasksInfo.setGeometry(QtCore.QRect(506, 9, 311, 81))
        self.tasksInfo.setObjectName("tasksInfo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.profileInfo.setText(_translate("MainWindow", "Profile"))
        self.additInterface.setWhatsThis(_translate("MainWindow", "Дополнительный интерфейс. Например, кнопка \"взяться за задание\""))
        self.tasksInfo.setText(_translate("MainWindow", "Tasks"))
